name: Identical Commit Status On Push

# To trigger the check
on: push
  
jobs:
  add-commit-status:
    runs-on: ubuntu-latest
    # permissions:
    #   checks: write   # Permission to create a Check Run
    #   contents: write # Permission to write a repository_dispatch requests
    steps:
      - name: Create Commit Status
        env:
          GH_TOKEN: ${{ github.token }} # Expose the token for GH CLI
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            -H "Authorization: Bearer ${{ github.token }} " \
            https://api.github.com/repos/${{ github.repository }}/statuses/${{ github.sha }} \
            -d '{"state":"success","target_url":"https://example.com/build/status","description":"Commit status on push succeeded!","context":"tyler/testing/identical-commit-status"}'
